@DeviceEmulatorWeb_HostAddress = http://localhost:5183

GET {{DeviceEmulatorWeb_HostAddress}}/api/newdevice/{{
  "properties": [
   {       "name": "SN",       "value": "232323"     }
  ]
}

###

GET {{DeviceEmulatorWeb_HostAddress}}/api/newdevice/{sn}

###
